name: Publish snapshots to maven

on:
  push
jobs:
  test-approvals:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - id: get_approvers
        run: |
          echo "approvers=$(cat .github/CODEOWNERS | grep '^/MAINTAINERS.md' | sed 's/^\/MAINTAINERS.md @//g' | tr -d '@' | tr ' ' ',' | tr -d '\n')" >> $GITHUB_OUTPUT
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ steps.get_approvers.outputs.approvers }}
          minimum-approvals: 1
          issue-title: 'Request to approve/deny benchmark run for PR #${{ env.PR_NUMBER }}'
          issue-body: "Please approve or deny the benchmark run for PR #${{ env.PR_NUMBER }}"
          exclude-workflow-initiator-as-approver: false
