name: Approval Workflow

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'The pull request number'
        required: true
        type: string

jobs:
  wait-for-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Approval Step
        run: echo "Manual approval required. Approve this job to continue."
        shell: bash
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}

  continue-on-approval:
    needs: wait-for-approval
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Details
        id: get_pr
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = parseInt('${{ github.event.inputs.pr_number }}');
            const { data: pull_request } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            return pull_request;

      - name: Checkout PR submitter's code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_pr.outputs.head_ref }}
          repository: ${{ steps.get_pr.outputs.head_repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Gradle check
        run: ./gradlew check

