---
name: gradle-check

on: [push, pull_request]

jobs:
  groovy-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v3
      - name: Run Gradle Check
        run: |
          ./gradlew check
