name: Test github checkout

on:
  issue_comment:
    types: [created]

jobs:
  run-on-issue-comment:
    if: ${{ (github.event.issue.pull_request) && (contains(github.event.comment.body, 'hello')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up PR Number Env
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Get PR Details
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const prNumber = issue.number;
            console.log(`Pull Request Number: ${prNumber}`);

            const { data: pull_request } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            return {
              "headRepoFullName": pull_request.head.repo.full_name,
              "headRef": pull_request.head.ref
            };

      - name: Read Output
        run: |
          echo '${{ steps.get_pr.outputs.result }}' | jq -r '.headRepoFullName'
          echo '${{ steps.get_pr.outputs.result }}' | jq -r '.headRef'
          headRepo=$(echo '${{ steps.get_pr.outputs.result }}' | jq -r '.headRepoFullName')
          headRef=$(echo '${{ steps.get_pr.outputs.result }}' | jq -r '.headRef')
          echo "myHeadRepo=$headRepo" >> $GITHUB_ENV
          Echo "headRef=$headRef" >> $GITHUB_ENV
      
      - name: Print ENV
        run: |
          cat $GITHUB_ENV
          echo "headRepoFullName: $myHeadRepo"

      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          repository: ${{ env.myHeadRepo }}
          ref: ${{ env.headRef }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Gradle Check
        run: |
          ./gradlew check


